build:
  maxIssues: 0
  excludeCorrectable: false
  failOnThreshold: 1

config:
  validation: true
  warningsAsErrors: true

complexity:
  active: true

coroutines:
  active: true

formatting:
  active: true

naming:
  active: true

performance:
  active: true

potential-bugs:
  active: true

style:
  active: true

Compose:
  Active: true
  ComposableAnnotationNaming:
    active: true
  ComposableNaming:
    active: true
  ComposableParamOrder:
    active: true
  CompositionLocalAllowlist:
    active: true
  ContentEmitterReturningValues:
    active: true
  DefaultsVisibility:
    active: true
  LambdaParameterInRestartableEffect:
    active: true
  Material2Design:
    active: false
  ModifierComposable:
    active: true
  ModifierComposed:
    active: true
  ModifierMissing:
    active: true
  ModifierNaming:
    active: true
  ModifierNotUsedAtRoot:
    active: true
  ModifierReused:
    active: true
  ModifierWithoutDefault:
    active: true
  MultipleEmitters:
    active: true
  MutableParams:
    active: true
  Naming:
    active: true
  NonRestartableSkippable:
    active: true
  PreviewAnnotationNaming:
    active: true
  PreviewPublic:
    active: true
  RememberMissing:
    active: true
  RestartableEffect:
    active: true
  StateNotRead:
    active: true
  UnnecessaryEvents:
    active: true
  ViewModelForwarding:
    active: true
  ViewModelInjection:
    active: true
